<?php

	$description = 'New notification';
	$mail = 'A new notification has been generated by the system.<br> Connects to the site to view its contents.<br><br> THIS IS AN AUTOMATIC MESSAGE, PLEASE DO NOT RESPOND';
	
?>